model_provider = "custom"
model = "gpt-5"
model_reasoning_effort = "high"
disable_response_storage = true
preferred_auth_method = "apikey"

[model_providers.custom]
name = "custom"
base_url = "https://your-upstream.example.com/openai"
wire_api = "responses"
