model_provider = "crs"
model = "gpt-5-codex"
model_reasoning_effort = "high"
disable_response_storage = true
preferred_auth_method = "apikey"
[model_providers.crs]
name = "crs"
base_url = "your base_url"
wire_api = "responses"
requires_openai_auth = true
env_key = "CRS_OAI_KEY"